#!/bin/bash

down()
{
	local DOWN="/etc/apache2/down.sh"

	if [ -f $DOWN ]
    then
    	 chmod +x $DOWN && chmod 755 $DOWN && eval $DOWN;
    fi

    exit
}

trap down SIGTERM

source /etc/apache2/envvars
exec /usr/sbin/apache2ctl -k restart -D FOREGROUND  > /dev/null 2>&1